// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zidkjsukkisiyetcrdwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppZGtqc3Vra2lzaXlldGNyZHdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTY3ODcsImV4cCI6MjA2NTU3Mjc4N30.AJdGo8Ussq3pgZ0xIz-X5VeD03JDcfJjyOgLwqt5-FU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);